sudo: required

matrix:
  include:
  - env: GHCVER=8.0.2
  - env: GHCVER=8.2.2
  - env: GHCVER=8.4.3
  - env: GHCVER=8.6.1
  - env: GHCVER=head

script:
- curl -sL https://raw.github.com/ndmitchell/neil/master/travis.sh | sh
